---
- hosts: all
  become: true
  pre_tasks:
   - name: install updates and upgrades for (CentOS)
     dnf:
             update_only: yes
             update_cache: yes
     when: ansible_distribution == "CentOS"
   - name: install updates and upgarades for (Ubuntu and Deb)
     apt:
             upgrade: dist
             update_cache: yes
     when: ansible_distribution in ["Ubuntu","Debian"]

  tasks:
  - name: install vim for Ubuntu
    apt:
      name: vim-nox 
      state: latest
    when: ansible_distribution in ["Ubuntu","Debian"]

  - name: install vim for CentOs
    dnf:
      name: vim-nox
      state: latest
    when: ansible_distribution == "CentOS"
